#!/usr/bin/env bash
#
# This module generates completion for the modules and its commands.

set -euo pipefail

#
# Const/Vars

readonly VERSION='1.0.0'

#
# Functions

usage() {
    cat <<EOF
Usage:
    oh completion [options] [command]

Commands:
    bash        Generate Bash completions.

Options:
    -h, --help  Show this help message and exit.

EOF
}

main() {
    case "${1:-}" in
        -h|--help|"")
            usage
            ;;
        -v | --version)
            printf '%s (OH module) version %s\n' "${0##*/}" "$VERSION"
            ;;
        -*)
            printf 'Unknown option: %s\n\n' "$1" >&2
            usage >&2
            exit 1
            ;;

        *)
            printf 'Unknown command: %s\n\n' "$1" >&2
            usage >&2
            exit 1
            ;;
    esac
}

#
# Entry point

main "$@"